minecraft:
    address: '172.21.64.1'
    port: '4711'
image:
    building_time_delay: 0.05
    size:
        max: 512
        min: 32
        default: 128
    height: 70
    default_colormap: one_value.grayscale
    blocks:
        one_value.grayscale:
            - [251, 15]
            - [173, 0]
            - [35, 15]
            - [251, 7]
            - [35, 7]
            - [159, 9]
            - [98, 0]
            - [4, 0]
            - [1, 0]
            - [1, 6]
            - [1, 5]
            - [35, 8]
            - [1, 4]
            - [42, 0]
            - [35, 0]
            - [80, 0]
        one_value.jet:
            - [251, 11]
            - [35, 11]
            - [22, 0]
            - [251, 3]
            - [35, 3]
            - [57, 0]
            - [35, 9]
            - [251, 9]
            - [159, 5]
            - [35, 13]
            - [251, 5]
            - [35, 5]
            - [251, 5]
            - [159, 4]
            - [251, 4]
            - [35, 4]
            - [41, 0]
            - [35, 4]
            - [251, 4]
            - [35, 1]
            - [251, 1]
            - [159, 1]
            - [159, 14]
            - [35, 14]
            - [251, 14]
            - [87, 0]
            - [215, 0]
            - [112, 0]
    